# Generated by Django 4.1.7 on 2023-03-26 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Аудитория')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Дисциплины',
                'verbose_name_plural': 'Дисциплина',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название группы')),
                ('letter', models.CharField(choices=[('1 Курс', '1 Курс'), ('2 Курс', '2 Курс'), ('3 Курс', '3 Курс'), ('4 Курс', '4 Курс'), ('5 Курс', '5 Курс'), ('6 Курс', '6 Курс')], default='', max_length=40, verbose_name='Курс')),
                ('count', models.CharField(max_length=10, null=True, verbose_name='Кол-во учиников')),
            ],
            options={
                'verbose_name': 'Группы',
                'verbose_name_plural': 'Группа',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='ФИО учителя')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raspis.discipline', verbose_name='')),
            ],
            options={
                'verbose_name': 'Учителя',
                'verbose_name_plural': 'Учитель',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата проведения пары')),
                ('letter', models.CharField(choices=[('Лекция', 'Лекция'), ('Семинар', 'Семинар'), ('Экзамен', 'Экзамен')], default='', max_length=40, verbose_name='Вид пары')),
                ('para', models.CharField(choices=[('8:00-9:30', '8:00-9:30'), ('9:40-11:10', '9:40-11:10'), ('11:20-12:50', '11:20-12:50'), ('13:00-14:30', '13:00-14:30'), ('14:40-16:10', '14:40-16:10'), ('16:20-17:50', '16:20-17:50')], default='А', max_length=50, verbose_name='Время')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raspis.discipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raspis.group', verbose_name='Группа')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raspis.teacher', verbose_name='ФИО учителя')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raspis.audience', verbose_name='Аудитория')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
    ]
